-- =========================================================
-- GEA Website — Supabase schema
-- Run this in the Supabase SQL editor for a fresh project.
-- =========================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------
-- ADMINS: auth users allowed into the hidden admin portal.
-- Add rows manually after creating the corresponding Supabase
-- Auth user (Authentication > Users > Add user).
-- ---------------------------------------------------------
create table if not exists admins (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create or replace function is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (select 1 from admins where auth_user_id = auth.uid());
$$;

create or replace function is_staff()
returns boolean
language sql
security definer
set search_path = public
as $$
  select
    exists (select 1 from admins where auth_user_id = auth.uid())
    or exists (select 1 from teacher_profiles where auth_user_id = auth.uid());
$$;

-- ---------------------------------------------------------
-- UPPERCLASSMEN: students allowed to log in and answer Q&A.
-- Add rows manually (name + school email + their Supabase
-- Auth user id) after creating their Auth account.
-- ---------------------------------------------------------
create table if not exists upperclassmen (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  school_email text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------
-- STUDENT PROFILES: the unified student account record.
-- Students sign up once, then their account data is reused for
-- dashboard access, Q&A, and leadership applications.
-- ---------------------------------------------------------
create table if not exists student_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique not null references auth.users(id) on delete cascade,
  auth_email text not null unique,
  full_name text not null,
  display_username text not null unique,
  graduating_class_year integer not null,
  student_id_number text not null unique,
  school_email text,
  can_answer_qa boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_profiles_auth_user_id_idx on student_profiles(auth_user_id);
create index if not exists student_profiles_display_username_idx on student_profiles(display_username);
create index if not exists student_profiles_full_name_idx on student_profiles(full_name);

-- ---------------------------------------------------------
-- STUDENT ACCOUNT REQUESTS: pending GEA student signups that
-- require admin approval before the real account is created.
-- ---------------------------------------------------------
create table if not exists student_account_requests (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  display_username text not null unique,
  school_email text not null unique,
  graduating_class_year integer not null,
  student_id_number text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  reviewed_by_auth_user_id uuid references auth.users(id) on delete set null,
  rejection_reason text,
  created_at timestamptz not null default now()
);

create index if not exists student_account_requests_status_idx on student_account_requests(status);
create index if not exists student_account_requests_school_email_idx on student_account_requests(school_email);

-- ---------------------------------------------------------
-- TEACHER PROFILES: private teacher accounts created with a
-- sign-up code, so staff can access the teacher portal.
-- ---------------------------------------------------------
create table if not exists teacher_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique not null references auth.users(id) on delete cascade,
  auth_email text not null unique,
  full_name text not null,
  school_email text not null unique,
  created_at timestamptz not null default now()
);

alter table teacher_profiles add column if not exists auth_email text;
alter table teacher_profiles add column if not exists full_name text;
alter table teacher_profiles add column if not exists school_email text;

create index if not exists teacher_profiles_auth_user_id_idx on teacher_profiles(auth_user_id);
create index if not exists teacher_profiles_school_email_idx on teacher_profiles(school_email);

-- ---------------------------------------------------------
-- TEACHER INVITES: one-time links generated by admins for a
-- specific teacher name/email. The invite is consumed once the
-- teacher creates their account.
-- ---------------------------------------------------------
create table if not exists teacher_invites (
  id uuid primary key default gen_random_uuid(),
  invite_token text not null unique,
  teacher_name text not null,
  teacher_email text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  used_auth_user_id uuid references auth.users(id) on delete set null,
  created_by_auth_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table teacher_invites add column if not exists invite_token text;
alter table teacher_invites add column if not exists teacher_name text;
alter table teacher_invites add column if not exists teacher_email text;
alter table teacher_invites add column if not exists expires_at timestamptz;
alter table teacher_invites add column if not exists used_at timestamptz;
alter table teacher_invites add column if not exists used_auth_user_id uuid references auth.users(id) on delete set null;
alter table teacher_invites add column if not exists created_by_auth_user_id uuid references auth.users(id) on delete set null;

create index if not exists teacher_invites_token_idx on teacher_invites(invite_token);
create index if not exists teacher_invites_teacher_email_idx on teacher_invites(teacher_email);
create index if not exists teacher_invites_used_at_idx on teacher_invites(used_at);

-- ---------------------------------------------------------
-- LEADERSHIP MEMBERS: filled seats on the leadership board.
-- Only rows that exist here show as "filled" on /leadership.
-- Seed the President row yourself; leave every other role
-- absent from this table until it's filled.
-- ---------------------------------------------------------
create table if not exists leadership_members (
  id uuid primary key default gen_random_uuid(),
  role text not null unique check (role in (
    'president','vice-president','secretary','publicist','treasurer',
    'rep-11','rep-10','rep-9'
  )),
  name text not null,
  contact_email text,
  bio text,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table leadership_members add column if not exists contact_email text;

-- ---------------------------------------------------------
-- STORAGE: leadership photos uploaded directly from the admin
-- portal and rendered publicly on /leadership.
-- ---------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('leadership-photos', 'leadership-photos', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'leadership_photos_public_read'
  ) then
    create policy leadership_photos_public_read
      on storage.objects
      for select
      using (bucket_id = 'leadership-photos');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'leadership_photos_staff_write'
  ) then
    create policy leadership_photos_staff_write
      on storage.objects
      for all
      using (bucket_id = 'leadership-photos' and is_staff())
      with check (bucket_id = 'leadership-photos' and is_staff());
  end if;
end
$$;

-- Example seed for the President seat — edit the name, then run:
-- insert into leadership_members (role, name, bio)
-- values ('president', 'Jaden [Last Name]', 'GEA President, Class of 2027');

-- ---------------------------------------------------------
-- APPLICATIONS: leadership role applications from students.
-- ---------------------------------------------------------
create table if not exists applications (
  id uuid primary key default gen_random_uuid(),
  role text not null,
  student_profile_id uuid references student_profiles(id) on delete set null,
  auth_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  display_username text,
  graduating_class_year integer,
  student_id_number text,
  school_email text not null,
  why_apply text not null,
  why_fit text not null,
  proof_of_work text,
  status text not null default 'pending'
    check (status in ('pending','reviewing','invited','interview_booked','approved','rejected')),
  interview_token uuid unique,
  invite_sent_at timestamptz,
  booked_slot_id uuid,
  created_at timestamptz not null default now()
);

alter table applications add column if not exists student_profile_id uuid references student_profiles(id) on delete set null;
alter table applications add column if not exists auth_user_id uuid references auth.users(id) on delete set null;
alter table applications add column if not exists display_username text;
alter table applications add column if not exists graduating_class_year integer;
alter table applications add column if not exists student_id_number text;

-- ---------------------------------------------------------
-- PROFILE CHANGE REQUESTS: user-submitted profile edits that
-- must be reviewed by admins before being applied.
-- ---------------------------------------------------------
create table if not exists profile_change_requests (
  id uuid primary key default gen_random_uuid(),
  profile_type text not null check (profile_type in ('student', 'teacher')),
  profile_id uuid not null,
  auth_user_id uuid references auth.users(id) on delete set null,
  requested_by_name text not null,
  current_fields jsonb not null,
  requested_fields jsonb not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  rejection_reason text,
  created_at timestamptz not null default now()
);

alter table profile_change_requests add column if not exists profile_type text not null default 'student';
alter table profile_change_requests add column if not exists profile_id uuid;
alter table profile_change_requests add column if not exists auth_user_id uuid references auth.users(id) on delete set null;
alter table profile_change_requests add column if not exists requested_by_name text;
alter table profile_change_requests add column if not exists current_fields jsonb;
alter table profile_change_requests add column if not exists requested_fields jsonb;
alter table profile_change_requests add column if not exists rejection_reason text;

-- ---------------------------------------------------------
-- INTERVIEW SLOTS: lunch-period interview times admins open up.
-- ---------------------------------------------------------
create table if not exists interview_slots (
  id uuid primary key default gen_random_uuid(),
  label text not null,             -- e.g. "Tuesday Lunch — Nov 12"
  slot_time timestamptz not null,
  is_booked boolean not null default false,
  application_id uuid references applications(id) on delete set null,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'applications_booked_slot_fk'
      and conrelid = 'applications'::regclass
  ) then
    alter table applications
      add constraint applications_booked_slot_fk
      foreign key (booked_slot_id) references interview_slots(id) on delete set null;
  end if;
end
$$;

-- ---------------------------------------------------------
-- Q&A: public questions + upperclassman answers, both gated
-- behind admin approval before they're shown publicly.
-- ---------------------------------------------------------
create table if not exists qa_questions (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  question_type text not null default 'general' check (question_type in ('general', 'math', 'word_problem')),
  forum_board text not null default 'general' check (forum_board in ('general', 'academics', 'projects', 'events', 'advice', 'life')),
  equation_lines text,
  work_text text,
  graph_notes text,
  graph_link text,
  asked_by_name text not null default 'Anonymous Student',
  asked_by_auth_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  upvote_count integer not null default 0,
  downvote_count integer not null default 0,
  report_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table qa_questions add column if not exists asked_by_auth_user_id uuid references auth.users(id) on delete set null;
alter table qa_questions add column if not exists question_type text not null default 'general';
alter table qa_questions add column if not exists forum_board text not null default 'general';
alter table qa_questions add column if not exists equation_lines text;
alter table qa_questions add column if not exists work_text text;
alter table qa_questions add column if not exists graph_notes text;
alter table qa_questions add column if not exists graph_link text;
alter table qa_questions add column if not exists rejection_reason text;
alter table qa_questions add column if not exists upvote_count integer not null default 0;
alter table qa_questions add column if not exists downvote_count integer not null default 0;
alter table qa_questions add column if not exists report_count integer not null default 0;

create index if not exists qa_questions_forum_board_idx on qa_questions(forum_board);

create table if not exists qa_question_votes (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references qa_questions(id) on delete cascade,
  voter_auth_user_id uuid not null references auth.users(id) on delete cascade,
  value integer not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  unique (question_id, voter_auth_user_id)
);

alter table qa_question_votes add column if not exists question_id uuid not null references qa_questions(id) on delete cascade;
alter table qa_question_votes add column if not exists voter_auth_user_id uuid not null references auth.users(id) on delete cascade;
alter table qa_question_votes add column if not exists value integer not null check (value in (-1, 1));

create table if not exists qa_question_reports (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references qa_questions(id) on delete cascade,
  reporter_auth_user_id uuid references auth.users(id) on delete cascade,
  reporter_key text not null default '',
  reason text not null default 'Community report',
  created_at timestamptz not null default now(),
  unique (question_id, reporter_key)
);

alter table qa_question_reports add column if not exists question_id uuid not null references qa_questions(id) on delete cascade;
alter table qa_question_reports add column if not exists reporter_auth_user_id uuid references auth.users(id) on delete cascade;
alter table qa_question_reports add column if not exists reporter_key text not null default '';
alter table qa_question_reports add column if not exists reason text not null default 'Community report';

create table if not exists qa_answers (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references qa_questions(id) on delete cascade,
  answer text not null,
  answered_by_name text not null,
  answered_by_auth_user_id uuid references auth.users(id) on delete set null,
  parent_answer_id uuid references qa_answers(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  upvote_count integer not null default 0,
  downvote_count integer not null default 0,
  report_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table qa_answers add column if not exists answered_by_auth_user_id uuid references auth.users(id) on delete set null;
alter table qa_answers add column if not exists parent_answer_id uuid references qa_answers(id) on delete cascade;
alter table qa_answers add column if not exists rejection_reason text;
alter table qa_answers add column if not exists upvote_count integer not null default 0;
alter table qa_answers add column if not exists downvote_count integer not null default 0;
alter table qa_answers add column if not exists report_count integer not null default 0;

create table if not exists qa_answer_votes (
  id uuid primary key default gen_random_uuid(),
  answer_id uuid not null references qa_answers(id) on delete cascade,
  voter_auth_user_id uuid not null references auth.users(id) on delete cascade,
  value integer not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  unique (answer_id, voter_auth_user_id)
);

alter table qa_answer_votes add column if not exists answer_id uuid not null references qa_answers(id) on delete cascade;
alter table qa_answer_votes add column if not exists voter_auth_user_id uuid not null references auth.users(id) on delete cascade;
alter table qa_answer_votes add column if not exists value integer not null check (value in (-1, 1));

create table if not exists qa_answer_reports (
  id uuid primary key default gen_random_uuid(),
  answer_id uuid not null references qa_answers(id) on delete cascade,
  reporter_auth_user_id uuid references auth.users(id) on delete cascade,
  reporter_key text not null default '',
  reason text not null default 'Community report',
  created_at timestamptz not null default now(),
  unique (answer_id, reporter_key)
);

alter table qa_answer_reports add column if not exists answer_id uuid not null references qa_answers(id) on delete cascade;
alter table qa_answer_reports alter column reporter_auth_user_id drop not null;
alter table qa_answer_reports add column if not exists reporter_key text not null default '';
alter table qa_answer_reports add column if not exists reason text not null default 'Community report';

update qa_question_reports
set reporter_key = coalesce(nullif(reporter_key, ''), reporter_auth_user_id::text, gen_random_uuid()::text)
where reporter_key = '' or reporter_key is null;

update qa_answer_reports
set reporter_key = coalesce(nullif(reporter_key, ''), reporter_auth_user_id::text, gen_random_uuid()::text)
where reporter_key = '' or reporter_key is null;

create unique index if not exists qa_question_reports_target_reporter_idx
  on qa_question_reports(question_id, reporter_key);
create unique index if not exists qa_answer_reports_target_reporter_idx
  on qa_answer_reports(answer_id, reporter_key);

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table leadership_members enable row level security;
alter table applications enable row level security;
alter table interview_slots enable row level security;
alter table qa_questions enable row level security;
alter table qa_question_votes enable row level security;
alter table qa_question_reports enable row level security;
alter table qa_answers enable row level security;
alter table qa_answer_votes enable row level security;
alter table qa_answer_reports enable row level security;
alter table upperclassmen enable row level security;
alter table student_profiles enable row level security;
alter table student_account_requests enable row level security;
alter table teacher_profiles enable row level security;
alter table teacher_invites enable row level security;
alter table admins enable row level security;
alter table profile_change_requests enable row level security;

-- Leadership: anyone can view the board; only admins can edit.
drop policy if exists "leadership_public_read" on leadership_members;
create policy "leadership_public_read" on leadership_members
  for select using (true);
drop policy if exists "leadership_admin_write" on leadership_members;
create policy "leadership_admin_write" on leadership_members
  for all using (is_staff()) with check (is_staff());

-- Applications: anyone can submit one; only admins can read/update.
-- (Public read is intentionally NOT allowed — applicant status and
-- interview details are only ever delivered through the token-based
-- RPC functions below, never a direct table read.)
drop policy if exists "applications_public_insert" on applications;
create policy "applications_public_insert" on applications
  for insert with check (true);
drop policy if exists "applications_admin_manage" on applications;
create policy "applications_admin_manage" on applications
  for select using (is_staff());
drop policy if exists "applications_self_read" on applications;
create policy "applications_self_read" on applications
  for select using (auth_user_id = auth.uid());
drop policy if exists "applications_admin_update" on applications;
create policy "applications_admin_update" on applications
  for update using (is_staff()) with check (is_staff());

drop policy if exists "student_profiles_self_read" on student_profiles;
create policy "student_profiles_self_read" on student_profiles
  for select using (auth_user_id = auth.uid() or is_staff());
drop policy if exists "student_profiles_self_update" on student_profiles;
create policy "student_profiles_self_update" on student_profiles
  for update using (auth_user_id = auth.uid() or is_staff()) with check (auth_user_id = auth.uid() or is_staff());
drop policy if exists "student_profiles_admin_write" on student_profiles;
create policy "student_profiles_admin_write" on student_profiles
  for all using (is_staff()) with check (is_staff());

drop policy if exists "student_account_requests_staff_read" on student_account_requests;
create policy "student_account_requests_staff_read" on student_account_requests
  for select using (is_staff());
drop policy if exists "student_account_requests_self_read" on student_account_requests;
create policy "student_account_requests_self_read" on student_account_requests
  for select using (lower(school_email) = lower(coalesce((auth.jwt() ->> 'email'), '')));
drop policy if exists "student_account_requests_staff_update" on student_account_requests;
create policy "student_account_requests_staff_update" on student_account_requests
  for update using (is_staff()) with check (is_staff());

drop policy if exists "teacher_profiles_self_read" on teacher_profiles;
create policy "teacher_profiles_self_read" on teacher_profiles
  for select using (auth_user_id = auth.uid() or is_staff());
drop policy if exists "teacher_profiles_self_update" on teacher_profiles;
create policy "teacher_profiles_self_update" on teacher_profiles
  for update using (auth_user_id = auth.uid() or is_staff()) with check (auth_user_id = auth.uid() or is_staff());
drop policy if exists "teacher_profiles_admin_write" on teacher_profiles;
create policy "teacher_profiles_admin_write" on teacher_profiles
  for all using (is_staff()) with check (is_staff());

drop policy if exists "teacher_invites_admin_manage" on teacher_invites;
create policy "teacher_invites_admin_manage" on teacher_invites
  for all using (is_staff()) with check (is_staff());

drop policy if exists "profile_change_requests_self_insert" on profile_change_requests;
create policy "profile_change_requests_self_insert" on profile_change_requests
  for insert with check (auth_user_id = auth.uid());
drop policy if exists "profile_change_requests_self_read" on profile_change_requests;
create policy "profile_change_requests_self_read" on profile_change_requests
  for select using (auth_user_id = auth.uid() or is_staff());
drop policy if exists "profile_change_requests_admin_update" on profile_change_requests;
create policy "profile_change_requests_admin_update" on profile_change_requests
  for update using (is_staff()) with check (is_staff());

-- Interview slots: anyone can see open times; only admins manage them.
drop policy if exists "slots_public_read" on interview_slots;
create policy "slots_public_read" on interview_slots
  for select using (true);
drop policy if exists "slots_admin_write" on interview_slots;
create policy "slots_admin_write" on interview_slots
  for all using (is_staff()) with check (is_staff());

-- Q&A questions: anyone can ask; anyone can read approved ones;
-- only admins can read pending ones or change status.
drop policy if exists "questions_public_insert" on qa_questions;
create policy "questions_public_insert" on qa_questions
  for insert with check (true);
drop policy if exists "questions_read_approved_or_admin" on qa_questions;
create policy "questions_read_approved_or_admin" on qa_questions
  for select using (status = 'approved' or asked_by_auth_user_id = auth.uid() or is_staff());
drop policy if exists "questions_admin_update" on qa_questions;
create policy "questions_admin_update" on qa_questions
  for update using (is_staff()) with check (is_staff());
drop policy if exists "questions_admin_delete" on qa_questions;
create policy "questions_admin_delete" on qa_questions
  for delete using (is_staff());

drop policy if exists "question_votes_auth_select" on qa_question_votes;
create policy "question_votes_auth_select" on qa_question_votes
  for select using (voter_auth_user_id = auth.uid() or is_staff());
drop policy if exists "question_votes_auth_insert" on qa_question_votes;
create policy "question_votes_auth_insert" on qa_question_votes
  for insert with check (auth.uid() is not null);
drop policy if exists "question_votes_auth_update" on qa_question_votes;
create policy "question_votes_auth_update" on qa_question_votes
  for update using (voter_auth_user_id = auth.uid() or is_staff()) with check (voter_auth_user_id = auth.uid() or is_staff());
drop policy if exists "question_votes_auth_delete" on qa_question_votes;
create policy "question_votes_auth_delete" on qa_question_votes
  for delete using (voter_auth_user_id = auth.uid() or is_staff());

drop policy if exists "question_reports_auth_select" on qa_question_reports;
create policy "question_reports_auth_select" on qa_question_reports
  for select using (reporter_auth_user_id = auth.uid() or is_staff());
drop policy if exists "question_reports_auth_insert" on qa_question_reports;
create policy "question_reports_auth_insert" on qa_question_reports
  for insert with check (auth.uid() is not null);
drop policy if exists "question_reports_auth_delete" on qa_question_reports;
create policy "question_reports_auth_delete" on qa_question_reports
  for delete using (reporter_auth_user_id = auth.uid() or is_staff());

-- Q&A answers: only signed-in upperclassmen can submit answers;
-- anyone can read approved ones; only admins moderate.
drop policy if exists "answers_upperclassman_insert" on qa_answers;
create policy "answers_upperclassman_insert" on qa_answers
  for insert with check (
    exists (select 1 from student_profiles s where s.auth_user_id = auth.uid())
    or exists (select 1 from teacher_profiles t where t.auth_user_id = auth.uid())
    or is_staff()
  );
drop policy if exists "answers_read_approved_or_admin" on qa_answers;
create policy "answers_read_approved_or_admin" on qa_answers
  for select using (status = 'approved' or answered_by_auth_user_id = auth.uid() or is_staff());
drop policy if exists "answers_admin_update" on qa_answers;
create policy "answers_admin_update" on qa_answers
  for update using (is_staff()) with check (is_staff());
drop policy if exists "answers_admin_delete" on qa_answers;
create policy "answers_admin_delete" on qa_answers
  for delete using (is_staff());

drop policy if exists "answer_votes_auth_select" on qa_answer_votes;
create policy "answer_votes_auth_select" on qa_answer_votes
  for select using (voter_auth_user_id = auth.uid() or is_staff());
drop policy if exists "answer_votes_auth_insert" on qa_answer_votes;
create policy "answer_votes_auth_insert" on qa_answer_votes
  for insert with check (auth.uid() is not null);
drop policy if exists "answer_votes_auth_update" on qa_answer_votes;
create policy "answer_votes_auth_update" on qa_answer_votes
  for update using (voter_auth_user_id = auth.uid() or is_staff()) with check (voter_auth_user_id = auth.uid() or is_staff());
drop policy if exists "answer_votes_auth_delete" on qa_answer_votes;
create policy "answer_votes_auth_delete" on qa_answer_votes
  for delete using (voter_auth_user_id = auth.uid() or is_staff());

drop policy if exists "answer_reports_auth_select" on qa_answer_reports;
create policy "answer_reports_auth_select" on qa_answer_reports
  for select using (reporter_auth_user_id = auth.uid() or is_staff());
drop policy if exists "answer_reports_auth_insert" on qa_answer_reports;
create policy "answer_reports_auth_insert" on qa_answer_reports
  for insert with check (auth.uid() is not null);
drop policy if exists "answer_reports_auth_delete" on qa_answer_reports;
create policy "answer_reports_auth_delete" on qa_answer_reports
  for delete using (reporter_auth_user_id = auth.uid() or is_staff());

-- Upperclassmen: a user can check their own row; admins manage all.
drop policy if exists "upperclassmen_self_read" on upperclassmen;
create policy "upperclassmen_self_read" on upperclassmen
  for select using (auth_user_id = auth.uid() or is_admin());
drop policy if exists "upperclassmen_admin_write" on upperclassmen;
create policy "upperclassmen_admin_write" on upperclassmen
  for all using (is_admin()) with check (is_admin());

-- Admins table: only admins can read/manage the admin list.
drop policy if exists "admins_admin_read" on admins;
create policy "admins_admin_read" on admins
  for select using (is_admin());

-- Keep student profile timestamps current whenever a row changes.
create or replace function set_student_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists student_profiles_set_updated_at on student_profiles;
create trigger student_profiles_set_updated_at
before update on student_profiles
for each row execute function set_student_profiles_updated_at();

create or replace function qa_text_is_flagged(p_text text)
returns boolean
language plpgsql
as $$
declare
  blocked_phrase text;
  blocked_phrases text[] := array[
    'buy now',
    'free money',
    'make money fast',
    'crypto pump',
    'casino',
    'onlyfans',
    'porn',
    'nude'
  ];
begin
  if p_text is null or btrim(p_text) = '' then
    return false;
  end if;

  if p_text ~* 'https?://|www\.' then
    return true;
  end if;

  foreach blocked_phrase in array blocked_phrases loop
    if position(lower(blocked_phrase) in lower(p_text)) > 0 then
      return true;
    end if;
  end loop;

  return false;
end;
$$;

create or replace function guard_qa_question_content()
returns trigger
language plpgsql
as $$
begin
  if qa_text_is_flagged(new.question) then
    raise exception 'This post looks like spam or unsafe content.';
  end if;

  return new;
end;
$$;

drop trigger if exists qa_questions_guard_content on qa_questions;
create trigger qa_questions_guard_content
before insert or update on qa_questions
for each row execute function guard_qa_question_content();

create or replace function sync_qa_question_vote_counts()
returns trigger
language plpgsql
as $$
declare
  affected_question_id uuid;
begin
  if tg_op = 'DELETE' then
    affected_question_id := old.question_id;
  else
    affected_question_id := new.question_id;
  end if;

  update qa_questions
  set upvote_count = coalesce((select count(*) from qa_question_votes where question_id = affected_question_id and value = 1), 0),
      downvote_count = coalesce((select count(*) from qa_question_votes where question_id = affected_question_id and value = -1), 0)
  where id = affected_question_id;

  if tg_op = 'UPDATE' and old.question_id is distinct from new.question_id then
    update qa_questions
    set upvote_count = coalesce((select count(*) from qa_question_votes where question_id = old.question_id and value = 1), 0),
        downvote_count = coalesce((select count(*) from qa_question_votes where question_id = old.question_id and value = -1), 0)
    where id = old.question_id;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists qa_question_votes_sync_counts on qa_question_votes;
create trigger qa_question_votes_sync_counts
after insert or update or delete on qa_question_votes
for each row execute function sync_qa_question_vote_counts();

create or replace function guard_qa_answer_content()
returns trigger
language plpgsql
as $$
begin
  if qa_text_is_flagged(new.answer) then
    raise exception 'This comment looks like spam or unsafe content.';
  end if;

  return new;
end;
$$;

drop trigger if exists qa_answers_guard_content on qa_answers;
create trigger qa_answers_guard_content
before insert or update on qa_answers
for each row execute function guard_qa_answer_content();

create or replace function sync_qa_answer_vote_counts()
returns trigger
language plpgsql
as $$
declare
  affected_answer_id uuid;
begin
  if tg_op = 'DELETE' then
    affected_answer_id := old.answer_id;
  else
    affected_answer_id := new.answer_id;
  end if;

  update qa_answers
  set upvote_count = coalesce((select count(*) from qa_answer_votes where answer_id = affected_answer_id and value = 1), 0),
      downvote_count = coalesce((select count(*) from qa_answer_votes where answer_id = affected_answer_id and value = -1), 0)
  where id = affected_answer_id;

  if tg_op = 'UPDATE' and old.answer_id is distinct from new.answer_id then
    update qa_answers
    set upvote_count = coalesce((select count(*) from qa_answer_votes where answer_id = old.answer_id and value = 1), 0),
        downvote_count = coalesce((select count(*) from qa_answer_votes where answer_id = old.answer_id and value = -1), 0)
    where id = old.answer_id;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists qa_answer_votes_sync_counts on qa_answer_votes;
create trigger qa_answer_votes_sync_counts
after insert or update or delete on qa_answer_votes
for each row execute function sync_qa_answer_vote_counts();

create or replace function sync_qa_answer_report_counts()
returns trigger
language plpgsql
as $$
declare
  affected_answer_id uuid;
begin
  if tg_op = 'DELETE' then
    affected_answer_id := old.answer_id;
  else
    affected_answer_id := new.answer_id;
  end if;

  update qa_answers
  set report_count = coalesce((select count(*) from qa_answer_reports where answer_id = affected_answer_id), 0)
  where id = affected_answer_id;

  if tg_op = 'UPDATE' and old.answer_id is distinct from new.answer_id then
    update qa_answers
    set report_count = coalesce((select count(*) from qa_answer_reports where answer_id = old.answer_id), 0)
    where id = old.answer_id;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists qa_answer_reports_sync_counts on qa_answer_reports;
create trigger qa_answer_reports_sync_counts
after insert or update or delete on qa_answer_reports
for each row execute function sync_qa_answer_report_counts();

create or replace function sync_qa_question_report_counts()
returns trigger
language plpgsql
as $$
declare
  affected_question_id uuid;
begin
  if tg_op = 'DELETE' then
    affected_question_id := old.question_id;
  else
    affected_question_id := new.question_id;
  end if;

  update qa_questions
  set report_count = coalesce((select count(*) from qa_question_reports where question_id = affected_question_id), 0)
  where id = affected_question_id;

  if tg_op = 'UPDATE' and old.question_id is distinct from new.question_id then
    update qa_questions
    set report_count = coalesce((select count(*) from qa_question_reports where question_id = old.question_id), 0)
    where id = old.question_id;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists qa_question_reports_sync_counts on qa_question_reports;
create trigger qa_question_reports_sync_counts
after insert or update or delete on qa_question_reports
for each row execute function sync_qa_question_report_counts();

-- =========================================================
-- RPC FUNCTIONS — the ONLY way the public interview page
-- touches application data, so a stolen table read can never
-- expose every applicant's info.
-- =========================================================

-- Look up minimal, non-sensitive info for the token-based booking page.
create or replace function get_application_by_token(p_token uuid)
returns table (
  role text,
  status text,
  booked_slot_id uuid
)
language sql
security definer
set search_path = public
as $$
  select role, status, booked_slot_id
  from applications
  where interview_token = p_token;
$$;

-- Book an open interview slot for a given token. Returns the label
-- of the slot booked, or raises an exception if it's unavailable.
create or replace function book_interview_slot(p_token uuid, p_slot_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_app_id uuid;
  v_label text;
begin
  select id into v_app_id from applications where interview_token = p_token;
  if v_app_id is null then
    raise exception 'Invalid interview link.';
  end if;

  update interview_slots
     set is_booked = true, application_id = v_app_id
   where id = p_slot_id and is_booked = false
   returning label into v_label;

  if v_label is null then
    raise exception 'That slot was just booked by someone else — please pick another.';
  end if;

  update applications
     set booked_slot_id = p_slot_id, status = 'interview_booked'
   where id = v_app_id;

  return v_label;
end;
$$;

grant execute on function get_application_by_token(uuid) to anon, authenticated;
grant execute on function book_interview_slot(uuid, uuid) to anon, authenticated;

-- Student login helpers: public lookup for username preview and sign-in resolution.
create or replace function search_student_profiles(p_query text)
returns table (
  auth_email text,
  full_name text,
  display_username text,
  graduating_class_year integer
)
language sql
security definer
set search_path = public
as $$
  select auth_email, full_name, display_username, graduating_class_year
  from student_profiles
  where p_query is not null
    and (
      lower(full_name) like lower(trim(p_query)) || '%'
      or lower(display_username) like lower(trim(p_query)) || '%'
      or lower(full_name) like '%' || lower(trim(p_query)) || '%'
      or lower(display_username) like '%' || lower(trim(p_query)) || '%'
    )
  order by
    case
      when lower(display_username) = lower(trim(p_query)) then 0
      when lower(full_name) = lower(trim(p_query)) then 1
      else 2
    end,
    created_at asc
  limit 5;
$$;

create or replace function resolve_student_login(p_handle text)
returns table (
  auth_email text,
  full_name text,
  display_username text,
  graduating_class_year integer
)
language sql
security definer
set search_path = public
as $$
  select auth_email, full_name, display_username, graduating_class_year
  from student_profiles
  where lower(display_username) = lower(trim(p_handle))
     or lower(full_name) = lower(trim(p_handle))
  order by
    case
      when lower(display_username) = lower(trim(p_handle)) then 0
      else 1
    end,
    created_at asc
  limit 1;
$$;

grant execute on function search_student_profiles(text) to anon, authenticated;
grant execute on function resolve_student_login(text) to anon, authenticated;
